version: '3.3'
services:
  app:
    image: node:18.20.4
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "${PORT}:3000"
    command: bash -c "npm install && npm run start:dev"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
