version: '3.3'
services:
  app:
    build: .
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "${PORT}:3000"
    env_file:
      - .env