version: '3.3'
services:
  app:
    build: .
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - db  
      
  db:
    image: mysql
    volumes:
      - warranty_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: warranty_bot
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
    - "3306:3306"

volumes:
  warranty_data:

      