version: '3.3'
services:
  app:
    image: node:18.20.4
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "${PORT}:3000"
    command: bash -c "npm install && npm run start:dev"
    env_file:
      - .env
    environment:
      - NODE_ENV=development